<?php

namespace App\Services\ProductService\Service;


use App\Models\Store\Product\Product;
use App\Services\ProductService\Support\Contract\ProductCreationContract;
use App\Services\ProductService\Support\Trait\HasProductPreparation;
use App\Services\ProductService\Support\Trait\HasProductVariation;

class Configurable extends AbstractProductType implements ProductCreationContract
{
    use HasProductPreparation,HasProductVariation;

    /**
     * @param array $data
     * @return bool|Product
     */
    public function create(array $data): bool|Product
    {
        // Prepare Data
        $cleanData = $this->prepareDataForProductCreation($this->getCleanProductData($data));
        // Create Parent Product
        $product =  Product::create($cleanData);
        // If Multiple Attributes Present
        return $this->createMultipleVariants($data,$product);
    }




    public function edit(Product $product, array $data): bool|Product
    {
        return parent::edit($product, $data); // TODO: Change the autogenerated stub
    }


}
