<?php

namespace App\Services\ProductService\Service;


use App\Models\Enums\PublishableCast;
use App\Models\Store\Attribute\FilterGroup;
use App\Models\Store\Product\Product;
use App\Services\ProductService\Support\Contract\ProductCreationContract;
use App\Services\ProductService\Support\Trait\HasProductPreparation;

class Simple extends AbstractProductType implements ProductCreationContract
{
    use HasProductPreparation;

    protected array $data = [];



    public function create(array $data):bool|Product
    {
        $this->data = $data;

        // Prepare Data
        $data = $this->prepareDataForProductCreation($data);
        // Create Product
        $product =  Product::create($data);

        // Fill Filter Attributes
        $group = FilterGroup::where(['id' => $product->filter_group_id])->with('filters')->first();
        foreach ($group->filters as $attribute) {
            $data['filter_attributes'][$attribute->code] = null;
        }
        $product->flat()->create([
            'sku' => $data['sku'],
            'filter_attributes' => $data['filter_attributes'],
        ]);

        return $product;
    }





    public function edit(Product $product, array $data): bool|Product
    {
        return parent::edit($product, $data); // TODO: Change the autogenerated stub
    }


}
