<?php

namespace Mintreu\LaravelProductCatalogue\Filament\Resources\ProductResource\Pages;


use App\Models\TaxCode;
use Filament\Actions;
use Filament\Forms;
use Filament\Resources\Pages\EditRecord;
use Mintreu\LaravelProductCatalogue\Casts\ProductTypeCast;
use Mintreu\LaravelProductCatalogue\Filament\Resources\ProductResource;
use Mintreu\LaravelProductCatalogue\Models\FilterGroup;
use Mintreu\LaravelProductCatalogue\Services\ProductUpdateService;


class EditProduct extends EditRecord
{
    protected static string $resource = ProductResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\ViewAction::make(),
            Actions\DeleteAction::make(),
        ];
    }


    public function getRelationManagers(): array
    {
        $relationManagers = [];
        if ($this->record->type == 'configurable') {
            $relationManagers[] = ProductResource\RelationManagers\VariantsRelationManager::class;
        }

        return $relationManagers;
    }



    public function mount(int|string $record): void
    {
        parent::mount($record);

        $this->record->load([
            'filterOptions',
            'filterOptions.filter',
        ]);
        if ($this->record->type == ProductTypeCast::CONFIGURABLE)
        {
            $this->record->load('variants.filterOptions.filter');
        }

        $data = $this->record->toArray();

        if ($this->record->type == ProductTypeCast::CONFIGURABLE) {
            // Collect all unique filter options from all variants
            $variantFilterOptions = $this->record->variants
                ->flatMap(fn($variant) => $variant->filterOptions)
                ->unique('id');

            if ($variantFilterOptions)
            {
                // Group them by filter ID and collect option IDs (array of IDs per filter)
                $filterOptionData = $variantFilterOptions
                    ->groupBy(fn($option) => $option->filter->id)
                    ->map(fn($group) => $group->pluck('id')->unique()->values()->toArray())
                    ->toArray();
            }
        } else {
            // For non-configurable: single option per filter
            $filterOptionData = collect($this->record->filterOptions)
                ->mapWithKeys(function ($option) {
                    return [
                        $option->filter->id => $option->id,
                    ];
                })->toArray();
        }

//
//
//        if ($this->record->type == ProductTypeCast::CONFIGURABLE)
//        {
//
//        }else{
//            // Correctly build nested 'filter_options' array
//            $filterOptionData = collect($this->record->filterOptions)->mapWithKeys(function ($option) {
//                return [
//                    $option->filter->id => $option->id,
//                ];
//            })->toArray();
//        }



        // Inject under 'filter_options' key
        $data['filter_options'] = $filterOptionData;

        $this->form->fill($data);
    }



    public function save(bool $shouldRedirect = true, bool $shouldSendSavedNotification = true): void
    {


         $this->record = ProductUpdateService::make($this->record)->update($this->form->getState());
         //dd($this->record);
         parent::save($shouldRedirect, $shouldSendSavedNotification); // TODO: Change the autogenerated stub
    }





//
//    public function form(Form $form): Form
//    {
//        return parent::form($form)
//            ->schema([
//
//
//
//
//
//            ]);
//    }













}
