<?php

namespace App\Filament\Resources\Ecommerce\Orders\Pages;

use App\Filament\Resources\Ecommerce\Orders\OrderResource;
use App\Filament\Resources\Ecommerce\Orders\Schemas\OrderCreationForm;
use Filament\Resources\Pages\CreateRecord;
use Filament\Schemas\Schema;
use Filament\Support\Enums\Width;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;
    protected Width | string | null $maxContentWidth = 'full';



    public function form(Schema $schema): Schema
    {
        return parent::form($schema)->schema(OrderCreationForm::fields()); // TODO: Change the autogenerated stub
    }


}
