<?php

namespace App\Filament\Resources\Users\Pages;

use Filament\Schemas\Schema;
use Filament\Forms\Components\TextInput;
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\ViewAction;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DissociateBulkAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Schemas\Components\Wizard;
use Filament\Schemas\Components\Wizard\Step;
use App\Casts\AuthStatusCast;
use App\Filament\Resources\Users\UserResource;
use App\Models\User;
use Filament\Forms;
use Filament\Resources\Pages\ManageRelatedRecords;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Blade;
use Illuminate\Support\HtmlString;


class ManageChildrens extends ManageRelatedRecords
{

    protected static string $resource = UserResource::class;

    protected static string $relationship = 'children';

    protected static string | \BackedEnum | null $navigationIcon = 'heroicon-o-users';
    protected static ?string $breadcrumb = 'Community';
    protected static ?string $title = 'Community';

    public static function getNavigationLabel(): string
    {
        return 'Community';
    }

    public static function shouldRegisterNavigation(array $parameters = []): bool
    {
//        dd($parameters);
//        if (filament()->auth()->user() instanceof User)
//        {
//            return filament()->auth()->user()->status == AuthStatusCast::SUBSCRIBED;
//        }
        return parent::shouldRegisterNavigation($parameters); // TODO: Change the autogenerated stub
    }


//    public static function getNavigationBadge(): ?string
//    {
//        return   (string) filament()->auth()->user()->descendants()->where('status',AuthStatusCast::SUBSCRIBED)->count() ;
//    }

    public function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextInput::make('name')
                    ->required()
                    ->maxLength(255),
            ]);
    }

    public function table(Table $table): Table
    {
        return $table
            ->query(fn() => $this->record->children())
            //->modifyQueryUsing(fn($query) => $query->where('status',AuthStatusCast::SUBSCRIBED))
            ->recordTitleAttribute('name')
            ->columns([
                TextColumn::make('name'),
                TextColumn::make('email'),
                TextColumn::make('mobile'),
                TextColumn::make('referral_code'),
            ])
            ->emptyStateHeading('No team members')
            ->emptyStateDescription('Create a team member to get started.')
            ->filters([
                //
            ])
            ->headerActions([


            ])
            ->recordActions([
//                Impersonate::make()
//                    ->model(fn(Model $record) => $record)
//                    ->requiresConfirmation()
//                    ->guard(PanelGuardCast::APP->getPanelGuard())
//                    ->visible(fn() => filament()->getCurrentPanel()->getId() == PanelGuardCast::ADMIN->value)
//                    ->failureRedirectUrl(fn() => self::$resource::getUrl())
//                    ->redirectTo(fn() => url(PanelGuardCast::APP->getPanelPath())),

                ViewAction::make()->url(fn(Model $record) => self::$resource::getUrl('view',['record' => $record->referral_code])),
//                Tables\Actions\EditAction::make(),
                //Tables\Actions\DeleteAction::make(),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DissociateBulkAction::make(),
                    DeleteBulkAction::make(),
                ]),
            ]);
    }




    public function getNewUserCreationForm(): array
    {
        return [
            Wizard::make([
                Step::make('Welcome')
                    ->schema($this->getParentSelectionFormSchema()),
                Step::make('Creation')
                    ->icon('heroicon-s-user-circle')
                    ->columns(3)
                    ->schema($this->getUserCreationFormSchema()),
                Step::make('Address')
                    ->icon('heroicon-s-map-pin')
                    ->columns(3)
                    ->schema($this->getAddressAccountFormSchema()),
                Step::make('Finish')
                    ->schema($this->UserCreationFinalPreviewSchema()),
            ])->submitAction(new HtmlString(Blade::render(<<<BLADE
                        <x-filament::button
                            type="submit"
                            size="sm"
                        >
                            Submit
                        </x-filament::button>
                    BLADE)))
                ->columnSpanFull(),
        ];
    }



}
