<?php

namespace App\Filament\Resources\Order\OrderResource\Pages;

use App\Casts\AuthStatusCast;
use App\Casts\AuthTypeCast;
use App\Filament\Resources\Order\OrderResource;
use App\Models\User;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Wizard;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Database\Eloquent\Collection;


class CreateOrder extends CreateRecord
{
    use OrderResource\Schema\HasOrderCreationFormSchema,CreateRecord\Concerns\HasWizard;
    protected static string $resource = OrderResource::class;
    protected ?Collection $orderAbleProducts = null;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub
        //$this->orderAbleProducts = Product::with('media')->where('status',PublishableStatusCast::PUBLISHED->value)->get();
    }


    public function form(Form $form): Form
    {
        return parent::form($form)
            ->schema([

                Wizard::make([
                    Wizard\Step::make('Customer')
                        ->schema([

                            Select::make('customer')
                                ->options(User::where('type','!=',AuthTypeCast::REGULAR->value)
                                    ->whereIn('status',[AuthStatusCast::SUBSCRIBED->value,AuthStatusCast::ACTIVE->value])
                                    ->get()->pluck('name','id')
                                )

                        ]),
                    Wizard\Step::make('Order')
                        ->schema([
                            $this->chooseProducts()
                        ]),
                    Wizard\Step::make('Delivery')
                        ->schema([
                            // ...
                        ]),
                    Wizard\Step::make('Billing')
                        ->schema([
                            // ...
                        ]),
                ])->columnSpanFull()


            ]); // TODO: Change the autogenerated stub
    }


}
