<?php

namespace App\Filament\Resources\Promotion\SaleResource\Pages;

use App\Filament\Resources\Promotion\SaleResource;
use App\Filament\Resources\Promotion\SaleResource\Schema\HasSaleConditionFormSchema;
use Filament\Forms\Form;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Collection;
use Mintreu\LaravelCommerinity\Support\SaleManager;

class CreateSale extends CreateRecord
{

    use HasSaleConditionFormSchema;

    protected static string $resource = SaleResource::class;
    protected SaleManager $saleManager;

    public ?Collection $conditions = null;

    public function mount(): void
    {
        $this->saleManager = SaleManager::make();
        $this->conditions = $this->saleManager->getCondition();

        //$this->fillForm();
        $data['Conditions_list'] = [
            'condition_type',
            'conditions' => [
                'attribute',
                'options',
                'value'
            ],
        ];
        $this->form->fill($data);
    }


    public function form(Form $form): Form
    {
        return parent::form($form)
            ->schema(array_merge(self::$resource::getCommonFormSchema(),$this->getSaleConditionFormSchema()));
    }

    protected function afterCreate(): void
    {
        $this->saleManager = $this->saleManager ?? SaleManager::make();
        $this->saleManager->reindexSaleableProducts();

    }

//    protected function mutateFormDataBeforeCreate(array $data): array
//    {
//        dd($data);
//        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
//    }


}
