<?php

namespace Mintreu\LaravelHelpdesk\Filament\Resources\HelpDeskResource\Pages;

use Filament\Resources\Pages\CreateRecord;
use Mintreu\LaravelHelpdesk\Filament\Resources\HelpDeskResource;

class CreateHelpDesk extends CreateRecord
{
    protected static string $resource = HelpDeskResource::class;






    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $loggedInUser = filament()->auth()->user();
        $data = array_merge($data,[
            'authorable_type' => get_class($loggedInUser),
            'authorable_id' => $loggedInUser->id,
        ]);

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
