<?php

namespace App\Filament\Resources\HelpDeskResource\Pages;

use App\Filament\Resources\HelpDeskResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateHelpDesk extends CreateRecord
{
    protected static string $resource = HelpDeskResource::class;





    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $loggedInUser = filament()->auth()->user();
        $data = array_merge($data,[
            'authorable_type' => get_class($loggedInUser),
            'authorable_id' => $loggedInUser->id,
        ]);

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
