<?php

namespace Mintreu\LaravelTransaction\Filament\Resources\BeneficiaryAccountResource\Pages;

use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Resources\Pages\CreateRecord;
use Mintreu\LaravelTransaction\Filament\Resources\BeneficiaryAccountResource;

class CreateBeneficiaryAccount extends CreateRecord
{
    use BeneficiaryAccountResource\Schemas\HasBeneficiaryCreationFormSchema;
    protected static string $resource = BeneficiaryAccountResource::class;



    public function form(Form $form): Form
    {
        return parent::form($form)
            ->schema($this->getBeneficiaryCreationFormSchema());
    }



    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // resolve wallet
        $accountableModel = $data['accountable_type'];
        $accountable = $accountableModel::with('wallet')->firstWhere('id',$data['accountable_id']);
        if ($accountable && $accountable->wallet)
        {
            $data['wallet_id'] = $accountable->wallet->id;
        }else{
            Notification::make()->title('Wallet missing!')->body($accountable->name.' has no wallet for connect')->warning()->send();
        }



        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
